### ISSUE TITLE
Password protected zip

### ISSUE THREAD

**Issue by think-free** [spkg/zipfs#1]
Is it possible to add the ability to serve file from a password protected zip file ?

https://github.com/yeka/zip

**Comment by jjeffery** [comment]
@think-free Thanks for your interest. This package makes use of the `archive/zip` package in the Go standard library, which does not support password-protected zip files. If this is something you would like to do, the quickest result would come from forking this repo and replacing use of the `archive/zip` package with the `yeka/zip` package.
